name: Setup Python and Build Docs

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[doc]

    - name: Clone sphinx-build
      run: git clone https://github.com/dtdang/docs-build.git

    - name: Set up environment variable
      run: echo "GITHUB_REPO=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)" >> $GITHUB_ENV
    
    - name: Build HTML artifact
      run: |
        cd sphinx-build
        python build_docs.py